### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by basz** [stefanpenner/broccoli-concat-analyser#18]
```
Livereload server on https://localhost:49155
The Broccoli Plugin: [BroccoliMergeTrees: styles] failed with:
TypeError: Cannot read property 'length' of undefined
    at /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-lab/node_modules/broccoli-concat/lib/strategies/simple.js:128:40
    at Array.reduce (native)
    at SimpleConcat.fileSizes (/Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-lab/node_modules/broccoli-concat/lib/strategies/simple.js:127:7)
    at Concat._doPatchBasedBuild (/Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-lab/node_modules/broccoli-concat/concat.js:152:33)
    at Concat.build (/Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-lab/node_modules/broccoli-concat/concat.js:104:17)
    at /Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-lab/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-lab/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-lab/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-lab/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/bas/Documents/Projects/PLHW.ProjectHealthyFeet/applications/hf-app-lab/node_modules/rsvp/dist/rsvp.js:2415:5)
```

**Comment by simonihmig** [comment]
@basz seems this issue should rather be created here: https://github.com/broccolijs/broccoli-concat! Closing this
