### ISSUE TITLE
TypeError: "buffer" argument must be a string, Buffer, TypedArray, or DataView

### ISSUE THREAD

**Issue by rwwagner90** [stefanpenner/broccoli-concat-analyser#26]
I'm not able to run this anymore. I get this:

```
processing: ./concat-stats-for11-app.js.json > ./concat-stats-for11-app.js.out.jsonzlib.js:138
    throw new TypeError('"buffer" argument must be a string, Buffer, ' +
    ^

TypeError: "buffer" argument must be a string, Buffer, TypedArray, or DataView
    at zlibBufferSync (zlib.js:138:11)
    at Object.deflateSync (zlib.js:588:14)
    at summary.files.Object.keys.map.relativePath (/Users/rwwagner/.nvm/versions/node/v8.7.0/lib/node_modules/broccoli-concat-analyser/lib/summarize.js:22:25)
    at Array.map (<anonymous>)
    at summarize (/Users/rwwagner/.nvm/versions/node/v8.7.0/lib/node_modules/broccoli-concat-analyser/lib/summarize.js:16:38)
    at entries.forEach.entry (/Users/rwwagner/.nvm/versions/node/v8.7.0/lib/node_modules/broccoli-concat-analyser/lib/summarize-all.js:13:5)
    at Array.forEach (<anonymous>)
    at summarizeAll (/Users/rwwagner/.nvm/versions/node/v8.7.0/lib/node_modules/broccoli-concat-analyser/lib/summarize-all.js:9:11)
    at Object.<anonymous> (/Users/rwwagner/.nvm/versions/node/v8.7.0/lib/node_modules/broccoli-concat-analyser/lib/cli.js:19:1)
    at Module._compile (module.js:624:30)
```

**Comment by stefanpenner** [comment]
Im not able to reproduce, but if a steps to reproduce are provided I will gladly reproduce and fix
