### ISSUE TITLE
issues with lazy engines

### ISSUE THREAD

**Issue by stefanpenner** [stefanpenner/broccoli-concat-analyser#6]
```
[node 11/03/16 10:29:12]   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
[node 11/03/16 10:29:12]                  ^
[node 11/03/16 10:29:12] 
[node 11/03/16 10:29:12] Error: ENOENT: no such file or directory, open 'concat-stats-for/undefined-engine-vendor.js/engines-dist/messaging-ext/assets/engine-vendor.js'
[node 11/03/16 10:29:12]     at Error (native)
[node 11/03/16 10:29:12]     at Object.fs.openSync (fs.js:549:18)
[node 11/03/16 10:29:12]     at Object.fs.readFileSync (fs.js:397:15)
[node 11/03/16 10:29:12]     at /Users/syeung/Documents/Development/new/voyager-web_trunk/node_modules/broccoli-concat-analyser/index.js:27:22
[node 11/03/16 10:29:12]     at Array.map (native)
[node 11/03/16 10:29:12]     at summarize (/Users/syeung/Documents/Development/new/voyager-web_trunk/node_modules/broccoli-concat-analyser/index.js:26:38)
[node 11/03/16 10:29:12]     at /Users/syeung/Documents/Development/new/voyager-web_trunk/node_modules/broccoli-concat-analyser/index.js:56:3
[node 11/03/16 10:29:12]     at Array.forEach (native)
[node 11/03/16 10:29:12]     at Object.<anonymous> (/Users/syeung/Documents/Development/new/voyager-web_trunk/node_modules/broccoli-concat-analyser/index.js:53:9)
[node 11/03/16 10:29:12]     at Module._compile (module.js:410:26)
```

**Comment by stefanpenner** [comment]
this isn't an issue, it was merely an outdated dependency. broccoli-concat needs to be `v3.0.5 + v2.3.8`
